# NUMPY 

So lets have a basic exercise on numpy. 

In [1]:
import numpy as np 

#### create an array of 10 tens 

In [41]:
a=np.array([10,10,10,10,10,10,10,10,10,10])

#### Create an array of all the odd integers from 100 to 200

In [39]:
a=[]
for i in range(100,200):
    if(i%2!=0):
        a.append(i)
a=np.array(a)

#### Create a 3x3 identity matrix

In [38]:
b=[]
for i in range(3):
    a=[]
    for j in range(3):
        if i==j:
            a.append(1)
        else:
            a.append(0)
    b.append(a)
b=np.array(b)

#### write a code that gives the output given below
 ** *Note! In order to not lose the output, make sure you don't code in the cell that is directly above the plot, there is an extra cell above that one which won't overwrite that plot!* **



In [49]:
a=[]
k=1
for i in range(5):
    s=[]
    for j in range(5):
        s.append(k)
        k=k+1
    a.append(s)
np.array(a)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [9]:
# your code here-


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Create a 4X4 matrix with values starting from 0

In [37]:
a=[]
k=0
for i in range(4):
    s=[]
    for j in range(4):
        s.append(k)
        k=k+1
    a.append(s)
a=np.array(a)

#### Use NumPy to generate an array of 9 random numbers sampled from a standard normal distribution

In [36]:
rn = np.random.normal(1,9,9)

In [43]:
j = np.arange(12,24).reshape(3,4)
j

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#### on the given above array 'j' , perform the given questions. 

#### 1. Get the standard deviation of the values in mat

In [44]:
c=np.std(j)
print(c)

3.452052529534663


#### 2. Get the sum of all the columns in mat

In [45]:
s=np.add(j[0],j[1])
s=np.add(s,j[2])
print(s)

[48 51 54 57]


#### 3. write a code that gives the following output given below.
** *Note! In order to not lose the output, make sure you don't code in the cell that is directly above the plot, there is an extra cell above that one which won't overwrite that plot!* **

In [46]:
a=[[13],[17],[21]]
np.array(a)

array([[13],
       [17],
       [21]])

In [17]:
# your code here-


array([[13],
       [17],
       [21]])

#### 4. Get the sum of all the values in mat

In [48]:
c=np.sum(j)
print(c)

210


# GLAD YOU COMPLETED THIS PART, GOOD LUCK AHEAD!!